version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    image: 'ds4u/multi-nginx'
    ports:
      - '3050:80'
    depends_on:
      - api
      - client
  api:
    image: 'ds4u/multi-server'
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      PGUSER: "postgres"
      PGHOST: "postgres"
      PGDATABASE: "postgres"
      PGPASSWORD: "postgres"
      PGPORT: 5432
    depends_on:
      - postgres
    tty: true
  client:
    image: 'ds4u/multi-client'
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - api
    tty: true  
  worker:
    image: 'ds4u/multi-worker'
    volumes:
      - /app/node_modules
      - ./worker:/app
    depends_on:
      - redis
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
